// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgfgyiraesalyhfwluej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnZmd5aXJhZXNhbHloZndsdWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1ODM5NDYsImV4cCI6MjA1NzE1OTk0Nn0._gII5JYMNd-MdA2QgYMhdl83bcIrjGiNS_8LZfvRa-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);